export interface IRetiros {
  C4C_PRODUCTRECIPIENTPARTYNAME: string;
  C4C_ID: string;
  C4C_NAME: string;
  C4C_DATAORIGINTYPECODETEXT: string;
  C4C_ESCALATIONSTATUSCODETEXT: string;
  C4C_SERVICEPRIORITYCODETEXT: string;
  C4C_SERVICEREQUESTUSERLIFECYCLESTATUSCODE: string;
  C4C_SERVICEREQUESTUSERLIFECYCLESTATUSCODETEXT: string;
  C4C_REQUESTCLOSEDDATETIMECONTENT: string;
  C4C_SERVICESUPPORTTEAMPARTYNAME: string;
  C4C_SERVICEEXECUTIONTEAMPARTYNAME: string;
  C4C_SERVICETERMSSERVICEISSUENAME: string;
  C4C_REPORTEDPARTYID: string;
  C4C_CREATIONDATETIME: string;
  C4C_LASTCHANGEDATETIME: string;
  C4C_OBJECTCATEGORYNAME: string;
  C4C_INCIDENTCATEGORYNAME: string;
  C4C_SERVICEREQUESTLIFECYCLESTATUSCODETEXT: string;
  C4C_REQUESTASSIGNMENTSTATUSCODETEXT: string;
  C4C_CUSEARCH2_KUT: string;
  C4C_ESTADODEPROCESAMIENTO_KUT: string;
  C4C_ESTADODEPROCESAMIENTO_KUTTEXT: string;
  C4C_MOTIVODEESTATUS2_KUTTEXT: string;
  C4C_SEGMENTO_KUTTEXT: string;
  C4C_TERNINALID_KUT: string;
  C4C_TIPOCLIENTE_KUTTEXT: string;
  C4C_TIPOLOGIA_KUTTEXT: string;
  C4C_UEN_KUTTEXT: string;
  C4C_Z1REGIONAL_CUST_HEADER_KUTTEXT: string;
  C4C_Z1SECCIONAL_CUST_HEADER_KUTTEXT: string;
  C4C_ZONA_KUTTEXT: string;
  C4C_CIUDAD_EMPLEADO: string;
  C4C_EMAIL_EMPLEADO: string;
  C4C_POSTALCODE: string;
  C4C_CD_MUNICIPIO_DANE: string;
  C4C_NM_GRUPO_EMPRESARIAL: string;
  C4C_FL_UEN_CODIGO_UNICO: string;
  C4C_NM_CADENA: string;
  C4C_NM_REGIONAL: string;
  C4C_NM_MARCA_AGREGADOR: string;
  C4C_NM_AGREGADOR_PASARELA: string;
  C4C_ID_EXTER: string;
  C4C_BUSINESSPARTNERFORMATTEDNAME: string;
  C4C_CREACION_NIT: string;
  C4C_CREACION_CU: string;
  C4C_CD_TERMINAL_LOGICA: string;
  C4C_NM_SECCIONAL_COMERCIAL: string;
  C4C_DESC_MCC: string;
  C4C_NM_UEN: string;
  C4C_DESC_CADENA: string;
  C4C_NM_PRODUCTO_RED: string;
  C4C_NM_TIPO_TERMINAL: string;
  C4C_CD_MODELO_AGRUPADO: string;
  C4C_NM_VERSION_ACTUAL: string;
  C4C_NM_TIPOLOGIA_CIUDAD: string;
  C4C_NM_REGISTRO_MULTICOMERCIO: string;
  C4C_NM_MARCA_AGREGADOR_TERM: string;
  C4C_NM_AGENCIAS: string;
  C4C_NM_LEALTAD_PUNTOS_COLOMBIA: string;
  C4C_NM_ENTIDAD_FINANCIERA: string;
  C4C_CD_SERIAL_DISPOSITIVO: string;
  C4C_DESC_SITUACION_TERMINAL: string;
  C4C_NM_SITUACION_TERMINAL: string;
  C4C_NM_TIPO_CORRESPONSAL_BANCARIO: string;
  C4C_NM_CLASIFICACION_CIUDAD: string;
  C4C_NM_CLASE_TERMINAL: string;
  C4C_NM_LINEA: string;
  C4C_NU_TRX_MES_ACT_APRO: string;
  C4C_NU_TRX_MES_ACT_MENOS1_APRO: string;
  C4C_NU_TRX_MES_ACT_MENOS2_APRO: string;
  C4C_NU_TRX_MES_ACT_NEG: string;
  C4C_NU_TRX_MES_ACT_MENOS1_NEG: string;
  C4C_NU_TRX_MES_ACT_MENOS2_NEG: string;
  ACCOUNT_NITSEARCH11_KUT: string;
  ACCOUNT_BUSINESSPARTNERFORMATTEDNAME: string;
  FSM_A_STATUSCHANGEREASON: string;
  FSM_A_CODE: string;
  FSM_A_EARLIESTSTARTDATETIME: string;
  FSM_A_LASTCHANGED: string;
  FSM_A_ENDDATETIME: string;
  FSM_A_CREATEDATETIME: string;
  FSM_A_STARTDATETIME: string;
  FSM_A_DUEDATETIME: string;
  FSM_A_REMARKS: string;
  FSM_A_STATUS: string;
  FSM_S_CODE: string;
  FSM_S_TYPENAME: string;
  FSM_S_EXTERNALID: string;
  FSM_S_PRIORITY: string;
  FSM_S_PROBLEMTYPENAME: string;
  FSM_S_STATUSNAME: string;
  FSM_S_ORIGINNAME: string;
  FSM_BP_EMAILADDRESS: string;
  FSM_BP_MOBILEPHONE: string;
  FSM_BP_OFFICEPHONE: string;
  FSM_DR_LOCATION_LATITUDE: string;
  FSM_DR_CITY: string;
  FSM_DR_STREET: string;
  FSM_DR_LOCATION_LONGITUDE: string;
  FSM_PR_FIRSTNAME: string;
  FSM_PR_LASTNAME: string;
  FSM_PR_USERNAME: string;
  FSM_E_NAME: string;
  UDF_BPO: string;
  UDF_BANCO_ADQUIRIENTE: string;
  UDF_BOLSA: string;
  UDF_CORRESPONSAL_BANCO: string;
  UDF_DIRECCION_COMERCIO: string;
  UDF_EQUIPMENT_STATUS: string;
  UDF_EXTERNALIDAD: string;
  UDF_HORA_CIERRE: string;
  UDF_HORA_PARADA_1: string;
  UDF_HORA_PARADA_2: string;
  UDF_LOCALIZADO: string;
  UDF_MAL_ESCALADO: string;
  UDF_NOMBRE_COMERCIAL: string;
  UDF_OBS_PARADA_DE_TIEMPO_1: string;
  UDF_OBS_PARADA_DE_TIEMPO_2: string;
  UDF_RAZON_VISITA_EXITOSA: string;
  UDF_RAZON_VISITA_FALLIDA: string;
  UDF_REGION: string;
  UDF_RETENCION: string;
  UDF_SOLUCION_VISITA_EXITOSA: string;
  UDF_TERMINAL_INTERVENIDA: string;
  ULTIMO: string;
  FL_VIGENTE: string;
  CD_CODIGO_UNICO: string;
  CD_MODELO_AGRUPADO: string;
  FC_ULT_TRX_3MESES: string;
}

export const retirosNames = [
  'C4C_PRODUCTRECIPIENTPARTYNAME',
  'C4C_ID',
  'C4C_NAME',
  'C4C_DATAORIGINTYPECODETEXT',
  'C4C_ESCALATIONSTATUSCODETEXT',
  'C4C_SERVICEPRIORITYCODETEXT',
  'C4C_SERVICEREQUESTUSERLIFECYCLESTATUSCODE',
  'C4C_SERVICEREQUESTUSERLIFECYCLESTATUSCODETEXT',
  'C4C_REQUESTCLOSEDDATETIMECONTENT',
  'C4C_SERVICESUPPORTTEAMPARTYNAME',
  'C4C_SERVICEEXECUTIONTEAMPARTYNAME',
  'C4C_SERVICETERMSSERVICEISSUENAME',
  'C4C_REPORTEDPARTYID',
  'C4C_CREATIONDATETIME',
  'C4C_LASTCHANGEDATETIME',
  'C4C_OBJECTCATEGORYNAME',
  'C4C_INCIDENTCATEGORYNAME',
  'C4C_SERVICEREQUESTLIFECYCLESTATUSCODETEXT',
  'C4C_REQUESTASSIGNMENTSTATUSCODETEXT',
  'C4C_CUSEARCH2_KUT',
  'C4C_ESTADODEPROCESAMIENTO_KUT',
  'C4C_ESTADODEPROCESAMIENTO_KUTTEXT',
  'C4C_MOTIVODEESTATUS2_KUTTEXT',
  'C4C_SEGMENTO_KUTTEXT',
  'C4C_TERNINALID_KUT',
  'C4C_TIPOCLIENTE_KUTTEXT',
  'C4C_TIPOLOGIA_KUTTEXT',
  'C4C_UEN_KUTTEXT',
  'C4C_Z1REGIONAL_CUST_HEADER_KUTTEXT',
  'C4C_Z1SECCIONAL_CUST_HEADER_KUTTEXT',
  'C4C_ZONA_KUTTEXT',
  'C4C_CIUDAD_EMPLEADO',
  'C4C_EMAIL_EMPLEADO',
  'C4C_POSTALCODE',
  'C4C_CD_MUNICIPIO_DANE',
  'C4C_NM_GRUPO_EMPRESARIAL',
  'C4C_FL_UEN_CODIGO_UNICO',
  'C4C_NM_CADENA',
  'C4C_NM_REGIONAL',
  'C4C_NM_MARCA_AGREGADOR',
  'C4C_NM_AGREGADOR_PASARELA',
  'C4C_ID_EXTER',
  'C4C_BUSINESSPARTNERFORMATTEDNAME',
  'C4C_CREACION_NIT',
  'C4C_CREACION_CU',
  'C4C_CD_TERMINAL_LOGICA',
  'C4C_NM_SECCIONAL_COMERCIAL',
  'C4C_DESC_MCC',
  'C4C_NM_UEN',
  'C4C_DESC_CADENA',
  'C4C_NM_PRODUCTO_RED',
  'C4C_NM_TIPO_TERMINAL',
  'C4C_CD_MODELO_AGRUPADO',
  'C4C_NM_VERSION_ACTUAL',
  'C4C_NM_TIPOLOGIA_CIUDAD',
  'C4C_NM_REGISTRO_MULTICOMERCIO',
  'C4C_NM_MARCA_AGREGADOR_TERM',
  'C4C_NM_AGENCIAS',
  'C4C_NM_LEALTAD_PUNTOS_COLOMBIA',
  'C4C_NM_ENTIDAD_FINANCIERA',
  'C4C_CD_SERIAL_DISPOSITIVO',
  'C4C_DESC_SITUACION_TERMINAL',
  'C4C_NM_SITUACION_TERMINAL',
  'C4C_NM_TIPO_CORRESPONSAL_BANCARIO',
  'C4C_NM_CLASIFICACION_CIUDAD',
  'C4C_NM_CLASE_TERMINAL',
  'C4C_NM_LINEA',
  'C4C_NU_TRX_MES_ACT_APRO',
  'C4C_NU_TRX_MES_ACT_MENOS1_APRO',
  'C4C_NU_TRX_MES_ACT_MENOS2_APRO',
  'C4C_NU_TRX_MES_ACT_NEG',
  'C4C_NU_TRX_MES_ACT_MENOS1_NEG',
  'C4C_NU_TRX_MES_ACT_MENOS2_NEG',
  'ACCOUNT_NITSEARCH11_KUT',
  'ACCOUNT_BUSINESSPARTNERFORMATTEDNAME',
  'FSM_A_STATUSCHANGEREASON',
  'FSM_A_CODE',
  'FSM_A_EARLIESTSTARTDATETIME',
  'FSM_A_LASTCHANGED',
  'FSM_A_ENDDATETIME',
  'FSM_A_CREATEDATETIME',
  'FSM_A_STARTDATETIME',
  'FSM_A_DUEDATETIME',
  'FSM_A_REMARKS',
  'FSM_A_STATUS',
  'FSM_S_CODE',
  'FSM_S_TYPENAME',
  'FSM_S_EXTERNALID',
  'FSM_S_PRIORITY',
  'FSM_S_PROBLEMTYPENAME',
  'FSM_S_STATUSNAME',
  'FSM_S_ORIGINNAME',
  'FSM_BP_EMAILADDRESS',
  'FSM_BP_MOBILEPHONE',
  'FSM_BP_OFFICEPHONE',
  'FSM_DR_LOCATION_LATITUDE',
  'FSM_DR_CITY',
  'FSM_DR_STREET',
  'FSM_DR_LOCATION_LONGITUDE',
  'FSM_PR_FIRSTNAME',
  'FSM_PR_LASTNAME',
  'FSM_PR_USERNAME',
  'FSM_E_NAME',
  'UDF_BPO',
  'UDF_BANCO_ADQUIRIENTE',
  'UDF_BOLSA',
  'UDF_CORRESPONSAL_BANCO',
  'UDF_DIRECCION_COMERCIO',
  'UDF_EQUIPMENT_STATUS',
  'UDF_EXTERNALIDAD',
  'UDF_HORA_CIERRE',
  'UDF_HORA_PARADA_1',
  'UDF_HORA_PARADA_2',
  'UDF_LOCALIZADO',
  'UDF_MAL_ESCALADO',
  'UDF_NOMBRE_COMERCIAL',
  'UDF_OBS_PARADA_DE_TIEMPO_1',
  'UDF_OBS_PARADA_DE_TIEMPO_2',
  'UDF_RAZON_VISITA_EXITOSA',
  'UDF_RAZON_VISITA_FALLIDA',
  'UDF_REGION',
  'UDF_RETENCION',
  'UDF_SOLUCION_VISITA_EXITOSA',
  'UDF_TERMINAL_INTERVENIDA',
  'ULTIMO',
  'FL_VIGENTE',
  'CD_CODIGO_UNICO',
  'CD_MODELO_AGRUPADO',
  'FC_ULT_TRX_3MESES',
];
